### ISSUE TITLE
dist_order_current view does not accept latitude or longitude

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/MAIN#8]
This view is currently incomplete. Needs to be fixed to accept latitude and longitude in the url.

**Comment by David-Egan** [comment]
Since GeoDjango is now in I can work on this and fix it in the next few days

**Comment by David-Egan** [comment]
I think this was fixed as a byproduct of other changes. What url is this view at?

**Comment by David-Egan** [comment]
Forgot to move this to closed. This is currently fixed in dev.
